# Usa la imagen oficial LTS de Jenkins como base
FROM jenkins/jenkins:lts

# Cambia a usuario root para poder instalar paquetes
USER root

# Instala el cliente Docker y agrega al usuario jenkins al grupo docker
RUN apt-get update && apt-get install -y docker.io && \
    usermod -aG docker jenkins && \
    rm -rf /var/lib/apt/lists/*

# Vuelve al usuario jenkins
USER jenkins


